/* Generated by `sidemantic gen sql`. Do not edit by hand. */
export interface GeneratedQueries {
  "SELECT orders.region, orders.revenue FROM orders": {
    row: { "region": string; "revenue": number };
    params: {};
  };
  "SELECT orders.channel, orders.order_count FROM orders": {
    row: { "channel": string; "order_count": number };
    params: {};
  };
}
