/* Generated by `sidemantic gen types`. Do not edit by hand. */

export const schema = {
  "models": {
    "orders": {
      "dimensions": {
        "channel": {
          "kind": "categorical",
          "ts": "string"
        },
        "created_at": {
          "kind": "time",
          "ts": "string",
          "grains": [
            "second",
            "minute",
            "hour",
            "day",
            "week",
            "month",
            "quarter",
            "year"
          ]
        },
        "customer_tier": {
          "kind": "categorical",
          "ts": "string"
        },
        "product_line": {
          "kind": "categorical",
          "ts": "string"
        },
        "region": {
          "kind": "categorical",
          "ts": "string"
        }
      },
      "metrics": {
        "gross_margin": {
          "agg": "sum",
          "ts": "number"
        },
        "order_count": {
          "agg": "count",
          "ts": "number"
        },
        "revenue": {
          "agg": "sum",
          "ts": "number"
        }
      }
    }
  },
  "topMetrics": []
} as const;

export type Schema = typeof schema;
