from __future__ import annotations

import json
from typing import Any

from . import ast as ast
from .ast import (
    Amp,
    AndAnd,
    Arrow,
    AstNodeKind,
    AstNodeSpan,
    Binary,
    BinaryOp,
    Blank,
    Boolean,
    BracketIdentToken,
    BracketRef,
    Caret,
    Colon,
    ColumnDef,
    Comma,
    CommentKind,
    DataTable,
    DataTableColumn,
    DataTableType,
    DateTime,
    DateTimeToken,
    DefineBlock,
    Definition,
    Dialect,
    DocCommentToken,
    Dot,
    Eof,
    Eq,
    EqEq,
    EvaluateStmt,
    Expr,
    FuncParam,
    FunctionCall,
    FunctionDef,
    Gt,
    Gte,
    HierarchyRef,
    Identifier,
    IdentToken,
    LBrace,
    LosslessParse,
    LParen,
    Lt,
    Lte,
    MeasureDef,
    Minus,
    ModelMetadata,
    ModelTable,
    ModelValidationCode,
    ModelValidationIssue,
    Neq,
    Number,
    NumberToken,
    Omitted,
    OrderKey,
    OrOr,
    Parameter,
    ParamToken,
    Paren,
    Plus,
    Query,
    QuotedIdentToken,
    RBrace,
    RecoveredItem,
    RecoveredQueryItem,
    RecoveryDiagnostic,
    RecoveryPhase,
    RecoveryResult,
    RParen,
    Semicolon,
    Slash,
    SortDirection,
    SourceComment,
    Span,
    Star,
    String,
    StringToken,
    TableColumnRef,
    TableConstructor,
    TableDef,
    TableName,
    TableRef,
    Token,
    TokenKind,
    Tuple,
    Unary,
    UnaryOp,
    ValidationCode,
    ValidationIssue,
    VarBlock,
    VarDecl,
    VarDef,
    VisualShape,
    VisualShapeAxis,
    VisualShapeColumn,
    VisualShapeGroup,
    format_expression,
    format_query,
    from_raw_expr,
    from_raw_query,
    from_raw_tokens,
    lex,
    parse_expression,
    parse_expression_lossless,
    parse_query,
    parse_query_lossless,
    recover_expression,
    recover_query,
    validate_expression,
    validate_expression_against_model,
    validate_query,
    validate_query_against_model,
)


def parse_expression_raw(text: str) -> Any:
    native = _native_module()
    return json.loads(native.parse_expression(text))


def parse_query_raw(text: str) -> Any:
    native = _native_module()
    return json.loads(native.parse_query(text))


def lex_raw(text: str) -> Any:
    native = _native_module()
    return json.loads(native.lex(text))


def _native_module():
    try:
        from . import _native
    except Exception as exc:  # pragma: no cover - exercised via import in runtime
        raise RuntimeError("sidemantic_dax native module is not available") from exc
    return _native


__all__ = [
    "Amp",
    "AndAnd",
    "Arrow",
    "AstNodeKind",
    "AstNodeSpan",
    "Binary",
    "BinaryOp",
    "Blank",
    "Boolean",
    "BracketIdentToken",
    "BracketRef",
    "Caret",
    "Colon",
    "ColumnDef",
    "Comma",
    "CommentKind",
    "DefineBlock",
    "Definition",
    "Dialect",
    "DateTime",
    "DateTimeToken",
    "DataTable",
    "DataTableColumn",
    "DataTableType",
    "DocCommentToken",
    "Dot",
    "Eof",
    "Eq",
    "EqEq",
    "EvaluateStmt",
    "Expr",
    "FuncParam",
    "FunctionDef",
    "FunctionCall",
    "Gt",
    "Gte",
    "HierarchyRef",
    "IdentToken",
    "Identifier",
    "LBrace",
    "LParen",
    "Lt",
    "Lte",
    "LosslessParse",
    "MeasureDef",
    "ModelMetadata",
    "ModelTable",
    "ModelValidationCode",
    "ModelValidationIssue",
    "Minus",
    "Neq",
    "Number",
    "NumberToken",
    "Omitted",
    "OrOr",
    "OrderKey",
    "Paren",
    "Parameter",
    "ParamToken",
    "Plus",
    "Query",
    "QuotedIdentToken",
    "RBrace",
    "RecoveredItem",
    "RecoveredQueryItem",
    "RecoveryDiagnostic",
    "RecoveryPhase",
    "RecoveryResult",
    "RParen",
    "Semicolon",
    "Slash",
    "SortDirection",
    "SourceComment",
    "Span",
    "Star",
    "String",
    "StringToken",
    "TableColumnRef",
    "TableConstructor",
    "TableDef",
    "TableName",
    "TableRef",
    "Token",
    "TokenKind",
    "Tuple",
    "Unary",
    "UnaryOp",
    "VarBlock",
    "VarDecl",
    "VarDef",
    "ValidationCode",
    "ValidationIssue",
    "VisualShape",
    "VisualShapeAxis",
    "VisualShapeColumn",
    "VisualShapeGroup",
    "ast",
    "from_raw_expr",
    "from_raw_query",
    "from_raw_tokens",
    "format_expression",
    "format_query",
    "lex",
    "lex_raw",
    "parse_expression",
    "parse_expression_lossless",
    "parse_expression_raw",
    "parse_query",
    "parse_query_lossless",
    "parse_query_raw",
    "recover_expression",
    "recover_query",
    "validate_expression",
    "validate_expression_against_model",
    "validate_query",
    "validate_query_against_model",
]
