from __future__ import annotations

from typing import Any

from . import ast as ast
from .ast import (
    Amp,
    AndAnd,
    Arrow,
    Binary,
    BinaryOp,
    Blank,
    Boolean,
    BracketIdentToken,
    BracketRef,
    Caret,
    Colon,
    ColumnDef,
    Comma,
    DefineBlock,
    Definition,
    DocCommentToken,
    Dot,
    Eof,
    Eq,
    EqEq,
    EvaluateStmt,
    Expr,
    FuncParam,
    FunctionCall,
    FunctionDef,
    Gt,
    Gte,
    HierarchyRef,
    Identifier,
    IdentToken,
    LBrace,
    LParen,
    Lt,
    Lte,
    MeasureDef,
    Minus,
    Neq,
    Number,
    NumberToken,
    OrderKey,
    OrOr,
    Parameter,
    ParamToken,
    Paren,
    Plus,
    Query,
    QuotedIdentToken,
    RBrace,
    RParen,
    Semicolon,
    Slash,
    SortDirection,
    Span,
    Star,
    String,
    StringToken,
    TableColumnRef,
    TableConstructor,
    TableDef,
    TableName,
    TableRef,
    Token,
    TokenKind,
    Unary,
    UnaryOp,
    VarBlock,
    VarDecl,
    VarDef,
    from_raw_expr,
    from_raw_query,
    from_raw_tokens,
    lex,
    parse_expression,
    parse_query,
)


def parse_expression_raw(text: str) -> Any:
    native = _native_module()
    return native.parse_expression(text)


def parse_query_raw(text: str) -> Any:
    native = _native_module()
    return native.parse_query(text)


def lex_raw(text: str) -> Any:
    native = _native_module()
    return native.lex(text)


def _native_module():
    try:
        from . import _native
    except Exception as exc:  # pragma: no cover - exercised via import in runtime
        raise RuntimeError("sidemantic_dax native module is not available") from exc
    return _native


__all__ = [
    "Amp",
    "AndAnd",
    "Arrow",
    "Binary",
    "BinaryOp",
    "Blank",
    "Boolean",
    "BracketIdentToken",
    "BracketRef",
    "Caret",
    "Colon",
    "ColumnDef",
    "Comma",
    "DefineBlock",
    "Definition",
    "DocCommentToken",
    "Dot",
    "Eof",
    "Eq",
    "EqEq",
    "EvaluateStmt",
    "Expr",
    "FuncParam",
    "FunctionDef",
    "FunctionCall",
    "Gt",
    "Gte",
    "HierarchyRef",
    "IdentToken",
    "Identifier",
    "LBrace",
    "LParen",
    "Lt",
    "Lte",
    "MeasureDef",
    "Minus",
    "Neq",
    "Number",
    "NumberToken",
    "OrOr",
    "OrderKey",
    "Paren",
    "Parameter",
    "ParamToken",
    "Plus",
    "Query",
    "QuotedIdentToken",
    "RBrace",
    "RParen",
    "Semicolon",
    "Slash",
    "SortDirection",
    "Span",
    "Star",
    "String",
    "StringToken",
    "TableColumnRef",
    "TableConstructor",
    "TableDef",
    "TableName",
    "TableRef",
    "Token",
    "TokenKind",
    "Unary",
    "UnaryOp",
    "VarBlock",
    "VarDecl",
    "VarDef",
    "ast",
    "from_raw_expr",
    "from_raw_query",
    "from_raw_tokens",
    "lex",
    "lex_raw",
    "parse_expression",
    "parse_expression_raw",
    "parse_query",
    "parse_query_raw",
]
