models:
  - name: products
    table: products
    description: Product catalog
    primary_key: product_id

    dimensions:
      - name: category
        type: categorical
        sql: category
        description: Product category

      - name: subcategory
        type: categorical
        sql: subcategory
        description: Product subcategory

      - name: brand
        type: categorical
        sql: brand
        description: Product brand

      - name: product_name
        type: categorical
        sql: name
        description: Product name

      - name: is_active
        type: categorical
        sql: is_active
        description: Whether product is currently available

      - name: price_tier
        type: categorical
        sql: |
          CASE
            WHEN price < 50 THEN 'budget'
            WHEN price < 200 THEN 'mid-range'
            WHEN price < 500 THEN 'premium'
            ELSE 'luxury'
          END
        description: Price tier based on product price

    metrics:
      - name: product_count
        agg: count
        description: Total number of products

      - name: avg_price
        agg: avg
        sql: price
        description: Average product price

      - name: active_product_count
        agg: count
        filters:
          - is_active = true
        description: Number of active products
