"""Generate compatibility summaries from machine-readable repository contracts."""

from __future__ import annotations

import argparse
from pathlib import Path

import yaml

from sidemantic.formats import semantic_formats

ROOT = Path(__file__).resolve().parents[1]
RUNTIME_CONTRACT = ROOT / "docs" / "runtime-conformance.yml"
RUNTIME_MATRIX = ROOT / "docs" / "runtime-feature-matrix.md"
ADAPTER_SUMMARY = ROOT / "docs" / "compatibility" / "index.md"


def _display_status(record: dict) -> str:
    status = record["status"].capitalize()
    detail = record.get("detail")
    return f"{status} — {detail}" if detail else status


def render_runtime_matrix(contract: dict) -> str:
    runtimes = contract["runtimes"]
    runtime_keys = list(runtimes)
    lines = [
        "# Runtime Feature Matrix",
        "",
        "<!-- Generated by scripts/generate_compatibility_docs.py from docs/runtime-conformance.yml. -->",
        "",
        "This matrix describes the checked runtime contract for native Sidemantic projects. A capability",
        "status is meaningful only within the lifecycle and scope of its runtime.",
        "",
        "## Runtime lifecycle",
        "",
        "| Runtime | Lifecycle | Scope |",
        "|---|---|---|",
    ]
    for runtime in runtimes.values():
        lines.append(f"| {runtime['label']} | {runtime['lifecycle'].capitalize()} | {runtime['scope']} |")

    headers = " | ".join(runtimes[key]["label"] for key in runtime_keys)
    lines.extend(
        [
            "",
            "Rust, DuckDB extension, and WASM surfaces are experimental even where an individual",
            "capability is fixture-backed. `Supported` does not promote an experimental runtime to stable.",
            "",
            "## Capability support",
            "",
            f"| Capability | {headers} |",
            f"|---|{'|'.join('---' for _ in runtime_keys)}|",
        ]
    )
    for capability in contract["capabilities"].values():
        cells = " | ".join(_display_status(capability[key]) for key in runtime_keys)
        lines.append(f"| {capability['label']} | {cells} |")

    lines.extend(["", "## Evidence", ""])
    for capability_name, capability in contract["capabilities"].items():
        lines.append(f"### {capability['label']}")
        lines.append("")
        for runtime_key in runtime_keys:
            record = capability[runtime_key]
            evidence = record.get("evidence", [])
            fixtures = record.get("fixtures")
            parts = [f"status: `{record['status']}`"]
            if evidence:
                links = ", ".join(f"[`{path}`](../{path})" for path in evidence)
                parts.append(f"evidence: {links}")
            if fixtures:
                if isinstance(fixtures, list):
                    fixture_text = ", ".join(f"`{name}`" for name in fixtures)
                else:
                    fixture_text = f"`{fixtures}` shared fixtures"
                parts.append(f"fixtures: {fixture_text}")
            lines.append(f"- {runtimes[runtime_key]['label']}: " + "; ".join(parts) + ".")
        lines.append("")

    lines.extend(
        [
            "## Status definitions",
            "",
            *[f"- `{name}`: {description}" for name, description in contract["status_legend"].items()],
            "",
            "Python/Pyodide is documented separately in [`pyodide.md`](pyodide.md). It runs the Python core",
            "surface in a browser and must not be conflated with the experimental Rust/WASM runtime above.",
            "",
        ]
    )
    return "\n".join(lines)


def _adapter_test_directory(name: str) -> str:
    if name == "sidemantic":
        return "sidemantic_adapter"
    return name.replace("-", "_")


def render_adapter_summary(root: Path = ROOT) -> str:
    lines = [
        "# Import Adapter Compatibility Summary",
        "",
        "<!-- Generated by scripts/generate_compatibility_docs.py from sidemantic/formats.py and repository tests. -->",
        "",
        "This is the complete registry-level summary for Python import adapters. `Registered` means the CLI",
        "can route the format to its adapter; it does not imply complete source-platform feature parity.",
        "Detailed compatibility documents describe field-level limitations where they exist.",
        "",
        "| Format | Aliases | Input | Extensions | Import | Export | Dedicated tests | Detailed compatibility |",
        "|---|---|---|---|---:|---:|---:|---|",
    ]
    for spec in semantic_formats():
        aliases = ", ".join(f"`{alias}`" for alias in spec.aliases) or "—"
        extensions = ", ".join(f"`{extension}`" for extension in spec.extensions) or "—"
        test_dir = root / "tests" / "adapters" / _adapter_test_directory(spec.name)
        test_count = len(list(test_dir.glob("test_*.py"))) if test_dir.exists() else 0
        detail_path = root / "docs" / "compatibility" / f"{spec.name}.md"
        if detail_path.exists():
            detail = f"[Detailed guide]({spec.name}.md)"
        else:
            detail = "Registry summary only"
        lines.append(
            f"| `{spec.name}` | {aliases} | `{spec.source_kind.value}` | {extensions} | Registered | "
            f"{'Yes' if spec.supports_export else 'No'} | {test_count} | {detail} |"
        )

    lines.extend(
        [
            "",
            "The native `sidemantic` adapter is included because it participates in the same conversion registry.",
            "Adapters without a detailed guide are intentionally labeled summary-only; their test count is an",
            "inventory signal, not a claim that every upstream feature is supported.",
            "",
        ]
    )
    return "\n".join(lines)


def generated_documents() -> dict[Path, str]:
    contract = yaml.safe_load(RUNTIME_CONTRACT.read_text())
    return {
        RUNTIME_MATRIX: render_runtime_matrix(contract),
        ADAPTER_SUMMARY: render_adapter_summary(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail if checked-in generated docs are stale")
    args = parser.parse_args()

    stale = []
    for path, content in generated_documents().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)

    if stale:
        parser.error("stale generated docs: " + ", ".join(str(path) for path in stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
