"""TypeScript codegen from a semantic layer.

Two generators emit one shared output contract (see ``sidemantic-wasm/client.d.ts``):

- :func:`generate_client_schema_ts` — the structured typed client (``sidemantic gen types``):
  an ``as const`` schema of every model's dimensions/metrics with their TS scalar types,
  consumed by ``createClient`` for autocomplete + typed result rows.
- :func:`generate_sql_types_ts` — sqlx-style typed semantic SQL (``sidemantic gen sql``):
  scans TypeScript sources for semantic-SQL literals, validates + types each via the query
  rewriter, and emits a ``GeneratedQueries`` interface keyed by the exact SQL string.

Field types are resolved with the same Postgres-type logic the catalog uses
(:mod:`sidemantic.core.catalog`), which is higher fidelity than the wasm wire format.
"""

from __future__ import annotations

import glob as _glob
import json
import re
from collections import Counter
from pathlib import Path
from typing import Any

from sidemantic.core.catalog import get_postgres_type_for_dimension, get_postgres_type_for_metric

# Default selectable grains for a time dimension when none are declared explicitly.
TIME_GRANULARITIES = ["second", "minute", "hour", "day", "week", "month", "quarter", "year"]

# Postgres/DuckDB data type -> TypeScript scalar tag. Anything not listed (VARCHAR,
# DATE, TIMESTAMP, ...) maps to "string" — time values come back as ISO strings.
_PG_TO_TS = {
    "BIGINT": "number",
    "NUMERIC": "number",
    "DECIMAL": "number",
    "DOUBLE": "number",
    "REAL": "number",
    "INTEGER": "number",
    "BOOLEAN": "boolean",
}

_PARAM_TS = {"string": "string", "number": "number", "date": "string", "yesno": "boolean", "unquoted": "string"}
# Type-correct literal stubs so a query with `{{ params }}` parses for analysis.
_PARAM_STUB = {"string": "'x'", "number": "0", "date": "'2000-01-01'", "yesno": "TRUE", "unquoted": "1"}

_PARAM_RE = re.compile(r"\{\{\s*(\w+)\s*\}\}")


def _pg_to_ts(pg_type: str) -> str:
    return _PG_TO_TS.get(pg_type.upper(), "string")


# ---------------------------------------------------------------------------
# Structured typed client: `sidemantic gen types`
# ---------------------------------------------------------------------------


def build_client_schema(layer) -> dict[str, Any]:
    """Build the ``schema`` payload: per-field ``kind``/``ts`` (+ grains) keyed by model."""
    models: dict[str, Any] = {}
    for model_name, model in sorted(layer.graph.models.items()):
        dimensions: dict[str, Any] = {}
        metrics: dict[str, Any] = {}
        for dimension in sorted(model.dimensions, key=lambda item: item.name):
            entry: dict[str, Any] = {
                "kind": dimension.type,
                "ts": _pg_to_ts(get_postgres_type_for_dimension(dimension.type, dimension.granularity)),
            }
            if dimension.type == "time":
                entry["grains"] = list(dimension.supported_granularities or TIME_GRANULARITIES)
            dimensions[dimension.name] = entry
        for metric in sorted(model.metrics, key=lambda item: item.name):
            metrics[metric.name] = {
                "agg": metric.agg,
                "ts": _pg_to_ts(get_postgres_type_for_metric(metric.agg)),
            }
        models[model_name] = {"dimensions": dimensions, "metrics": metrics}

    model_metric_names = {metric.name for model in layer.graph.models.values() for metric in model.metrics}
    top_metrics = sorted(name for name in layer.graph.metrics if name not in model_metric_names)
    return {"models": models, "topMetrics": top_metrics}


def generate_client_schema_ts(layer, *, include_yaml: bool = True) -> str:
    """Generate a self-contained typed-client schema module from the semantic layer."""
    schema = build_client_schema(layer)
    schema_json = json.dumps(schema, indent=2)
    parts = [
        "/* Generated by `sidemantic gen types`. Do not edit by hand. */",
        "",
        f"export const schema = {schema_json} as const;",
        "",
        "export type Schema = typeof schema;",
    ]
    if include_yaml:
        from sidemantic.rust_bridge import graph_to_rust_yaml

        yaml_text = graph_to_rust_yaml(layer.graph)
        parts += ["", f"export const SCHEMA_YAML = {json.dumps(yaml_text)} as const;"]
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# sqlx-style typed semantic SQL: `sidemantic gen sql`
# ---------------------------------------------------------------------------


def expand_sources(patterns) -> list[Path]:
    """Resolve files/dirs/globs to a deduped list of TypeScript source files (excludes .d.ts)."""
    candidates: list[Path] = []
    for pattern in patterns or []:
        path = Path(pattern)
        if path.is_dir():
            candidates.extend(sorted(path.rglob("*.ts")))
            candidates.extend(sorted(path.rglob("*.tsx")))
        elif path.is_file():
            candidates.append(path)
        else:
            candidates.extend(Path(match) for match in sorted(_glob.glob(str(pattern), recursive=True)))

    files: list[Path] = []
    seen: set[Path] = set()
    for candidate in candidates:
        if not candidate.is_file() or candidate.name.endswith(".d.ts"):
            continue
        resolved = candidate.resolve()
        if resolved not in seen:
            seen.add(resolved)
            files.append(candidate)
    return files


def extract_sql_literals(files, *, call: str = "query") -> list[str]:
    """Extract semantic-SQL string/template literals passed to ``<call>(...)`` in TS sources.

    Captures backtick, double-, and single-quoted first arguments. Skips literals with
    JS interpolation (``${...}``) or backslash escapes — those are not statically typeable.
    """
    pattern = re.compile(r"\b" + re.escape(call) + r"\s*\(\s*(`[^`]*`|\"[^\"]*\"|'[^']*')", re.DOTALL)
    literals: list[str] = []
    for file in files:
        text = Path(file).read_text()
        for match in pattern.finditer(text):
            content = match.group(1)[1:-1]
            if not content or "${" in content or "\\" in content:
                continue
            if content not in literals:
                literals.append(content)
    return literals


def _param_type(layer, name: str) -> str | None:
    params = getattr(layer.graph, "parameters", {}) or {}
    parameter = params.get(name)
    return getattr(parameter, "type", None) if parameter is not None else None


def _extract_param_names(sql: str) -> list[str]:
    names: list[str] = []
    for name in _PARAM_RE.findall(sql):
        if name not in names:
            names.append(name)
    return names


def _stub_params(sql: str, layer) -> str:
    return _PARAM_RE.sub(lambda match: _PARAM_STUB.get(_param_type(layer, match.group(1)), "'x'"), sql)


def _ref_ts_type(graph, ref: str) -> str:
    """Resolve a projected ref (``model.field``, ``model.field__grain``, or bare metric) to a TS type."""
    if "." not in ref:
        metric = getattr(graph, "metrics", {}).get(ref)
        if metric is not None:
            return _pg_to_ts(get_postgres_type_for_metric(getattr(metric, "agg", None)))
        return "number"
    model_name, rest = ref.split(".", 1)
    field_name, _, grain = rest.partition("__")
    model = graph.models.get(model_name)
    if model is not None:
        dimension = next((item for item in model.dimensions if item.name == field_name), None)
        if dimension is not None:
            return _pg_to_ts(get_postgres_type_for_dimension(dimension.type, grain or dimension.granularity))
        metric = next((item for item in model.metrics if item.name == field_name), None)
        if metric is not None:
            return _pg_to_ts(get_postgres_type_for_metric(metric.agg))
    graph_metric = getattr(graph, "metrics", {}).get(field_name)
    if graph_metric is not None:
        return _pg_to_ts(get_postgres_type_for_metric(getattr(graph_metric, "agg", None)))
    return "number"


def _has_time_dimension(graph, dim_ref: str) -> bool:
    if "." not in dim_ref:
        return False
    model_name, rest = dim_ref.split(".", 1)
    field_name = rest.split("__", 1)[0]
    model = graph.models.get(model_name)
    if model is None:
        return False
    dimension = next((item for item in model.dimensions if item.name == field_name), None)
    return dimension is not None and dimension.type == "time"


def _apply_default_time_dimensions(graph, metrics: list[str], dimensions: list[str]) -> list[str]:
    result = list(dimensions)
    models_with_time_dims = {dim_ref.split(".", 1)[0] for dim_ref in dimensions if _has_time_dimension(graph, dim_ref)}
    seen_models: set[str] = set()
    for metric_ref in metrics:
        if "." not in metric_ref:
            continue
        model_name, _ = metric_ref.split(".", 1)
        if model_name in seen_models or model_name in models_with_time_dims:
            continue
        seen_models.add(model_name)
        model = graph.models.get(model_name)
        default_time_dimension = getattr(model, "default_time_dimension", None) if model is not None else None
        if not default_time_dimension:
            continue
        dim_ref = f"{model_name}.{default_time_dimension}"
        if getattr(model, "default_grain", None):
            dim_ref = f"{dim_ref}__{model.default_grain}"
        if dim_ref not in result:
            result.append(dim_ref)
        models_with_time_dims.add(model_name)
    return result


def _ref_alias(ref: str, explicit: dict[str, str]) -> str:
    if ref in explicit:
        return explicit[ref]
    if "." not in ref:
        return ref
    return ref.split(".", 1)[1]


def _output_columns(graph, explanation) -> list[tuple[str, str]]:
    """Output columns in projection order (dimensions, then metrics) with collision-aware aliases."""
    metrics = list(explanation.metrics)
    dimensions = _apply_default_time_dimensions(graph, metrics, list(explanation.dimensions))
    refs = dimensions + metrics
    explicit = explanation.aliases or {}
    base_aliases = [_ref_alias(ref, explicit) for ref in refs]
    counts = Counter(base_aliases)
    columns: list[tuple[str, str]] = []
    for ref, alias in zip(refs, base_aliases):
        if "." in ref and ref not in explicit and counts[alias] > 1:
            alias = f"{ref.split('.', 1)[0]}_{alias}"
        columns.append((alias, _ref_ts_type(graph, ref)))
    return columns


def analyze_sql(layer, sql: str) -> tuple[list[tuple[str, str]], dict[str, str]]:
    """Validate a semantic-SQL literal and return its (output columns, param) TS types.

    Raises ``ValueError`` (via the rewriter, strict mode) on invalid SQL or unknown refs —
    this is the build-time gate.
    """
    from sidemantic.sql.query_rewriter import QueryRewriter

    param_names = _extract_param_names(sql)
    rewriter = QueryRewriter(layer.graph, dialect=getattr(layer, "dialect", "duckdb"))
    explanation = rewriter.explain(_stub_params(sql, layer), strict=True)
    columns = _output_columns(layer.graph, explanation)
    params = {name: _PARAM_TS.get(_param_type(layer, name), "string") for name in param_names}
    return columns, params


def _ts_object(pairs) -> str:
    pairs = list(pairs)
    if not pairs:
        return "{}"
    return "{ " + "; ".join(f"{json.dumps(name)}: {ts}" for name, ts in pairs) + " }"


def generate_sql_types_ts(layer, queries) -> str:
    """Generate a ``GeneratedQueries`` interface from semantic-SQL literals."""
    entries = []
    param_type_entries = []
    for sql in queries:
        columns, params = analyze_sql(layer, sql)
        entries.append(
            f"  {json.dumps(sql)}: {{\n    row: {_ts_object(columns)};\n    params: {_ts_object(params.items())};\n  }};"
        )
        param_types = {name: _param_type(layer, name) or "string" for name in params}
        param_type_entries.append(f"  {json.dumps(sql)}: {json.dumps(param_types, sort_keys=True)},")
    body = "\n".join(entries)
    param_type_body = "\n".join(param_type_entries)
    return (
        "/* Generated by `sidemantic gen sql`. Do not edit by hand. */\n"
        "export interface GeneratedQueries {\n"
        f"{body}\n"
        "}\n"
        "\n"
        "export const queryParamTypes = {\n"
        f"{param_type_body}\n"
        "} as const;\n"
    )
