project:
  type: website
  resources:
    - assets/**

# Enable marimo extension for interactive cells with per-page pyproject
filters:
  - marimo-team/marimo

website:
  title: "Sidemantic"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Interactive Tour"
        href: marimo-interactive.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "Core Concepts"
        menu:
          - text: "Models"
            href: models.qmd
          - text: "Metrics"
            href: metrics.qmd
          - text: "Relationships"
            href: relationships.qmd
          - text: "SQL Queries"
            href: sql-queries.qmd
      - text: "Reference"
        menu:
          - text: "Python API"
            href: python-api.qmd
          - text: "YAML Format"
            href: YAML_FORMAT.md
          - text: "Format Adapters"
            href: adapters.qmd
          - text: "Gotchas"
            href: GOTCHAS.md
      - text: "Examples"
        href: examples.qmd

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
