project:
  type: website

website:
  title: "Sidemantic"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "Examples"
        href: examples.qmd
      - text: "Reference"
        menu:
          - text: "YAML Format"
            href: YAML_FORMAT.md
          - text: "Gotchas"
            href: GOTCHAS.md

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
