project:
  type: website

website:
  title: "Sidemantic"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "Core Concepts"
        menu:
          - text: "Models"
            href: models.qmd
          - text: "Measures"
            href: measures.qmd
          - text: "Joins"
            href: joins.qmd
          - text: "SQL Queries"
            href: sql-queries.qmd
      - text: "Examples"
        href: examples.qmd
      - text: "Reference"
        menu:
          - text: "Python API"
            href: python-api.qmd
          - text: "YAML Format"
            href: YAML_FORMAT.md
          - text: "Gotchas"
            href: GOTCHAS.md

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
