project:
  type: website
  output-dir: _site
  resources:
    - assets/**
    - CNAME
    - llms.txt
  pre-render:
    - uv run python generate_llms_txt.py

# Enable marimo extension for interactive cells with per-page pyproject
filters:
  - marimo-team/marimo

website:
  title: "Sidemantic"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      # - text: "Interactive Demo"
      #   href: dashboard.qmd
      - text: "Getting Started"
        href: getting-started.qmd
      - text: "Adapters"
        href: adapters.qmd
      - text: "Core Concepts"
        menu:
          - text: "Configuration"
            href: config.qmd
          - text: "Connections"
            href: connections.qmd
          - text: "Models"
            href: models.qmd
          - text: "Metrics"
            href: metrics.qmd
          - text: "Relationships"
            href: relationships.qmd
          - text: "Query"
            href: query.qmd
          - text: "Pre-Aggregations"
            href: pre-aggregations.qmd
      - text: "CLI"
        menu:
          - text: "Overview"
            href: cli.qmd
          - text: "Migrator"
            href: migrator.qmd
          - text: "Pre-Aggregation Recommendations"
            href: preagg-recommendations.qmd
          - text: "Workbench"
            href: workbench.qmd
          - text: "MCP Server"
            href: mcp-server.qmd
      - text: "Reference"
        menu:
          - text: "Python API"
            href: python-api.qmd
          - text: "YAML Format"
            href: YAML_FORMAT.md
          - text: "Gotchas"
            href: GOTCHAS.md
      - text: "Examples"
        href: examples.qmd
    right:
      - icon: github
        href: https://github.com/sidequery/sidemantic

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    include-in-header: _includes/posthog.html
    css: _includes/custom.css
