// In-browser / Node TypeScript codegen, the JS counterpart to `sidemantic gen types`.
// Runs the wasm to introspect a semantic layer and emits the same `as const` schema
// the Python generator produces (byte-identical for the client schema), so either
// generator can feed the shared `sidemantic-wasm/client` runtime.

import { createSidemanticRuntime } from "./index.js";

const TIME_GRANULARITIES = ["second", "minute", "hour", "day", "week", "month", "quarter", "year"];

// Postgres/DuckDB data type -> TS scalar tag (mirrors sidemantic-wasm/client ScalarTag).
const PG_TO_TS = {
  BIGINT: "number",
  NUMERIC: "number",
  DECIMAL: "number",
  DOUBLE: "number",
  REAL: "number",
  INTEGER: "number",
  BOOLEAN: "boolean",
};

function pgToTs(pgType) {
  return PG_TO_TS[String(pgType).toUpperCase()] || "string";
}

// Mirror sidemantic/core/catalog.py exactly so JS output matches the Python generator.
function pgForDimension(dimType, granularity) {
  if (dimType === "categorical") return "VARCHAR";
  if (dimType === "numeric") return "NUMERIC";
  if (dimType === "time") return ["day", "week", "month", "quarter", "year"].includes(granularity) ? "DATE" : "TIMESTAMP";
  if (dimType === "boolean") return "BOOLEAN";
  return "VARCHAR";
}

function pgForMetric(agg) {
  return agg === "count" || agg === "count_distinct" ? "BIGINT" : "NUMERIC";
}

function byName(a, b) {
  return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
}

/** Build the `schema` payload from a parsed wasm graph (matches build_client_schema in Python). */
export function buildClientSchema(graph) {
  const modelList = [...(graph.models || [])].sort(byName);
  const modelMetricNames = new Set();
  for (const model of modelList) for (const metric of model.metrics || []) modelMetricNames.add(metric.name);

  const models = {};
  for (const model of modelList) {
    const dimensions = {};
    for (const dimension of [...(model.dimensions || [])].sort(byName)) {
      const entry = { kind: dimension.type, ts: pgToTs(pgForDimension(dimension.type, dimension.granularity)) };
      if (dimension.type === "time") {
        const grains = dimension.supported_granularities;
        entry.grains = grains && grains.length ? grains : TIME_GRANULARITIES;
      }
      dimensions[dimension.name] = entry;
    }
    const metrics = {};
    for (const metric of [...(model.metrics || [])].sort(byName)) {
      metrics[metric.name] = { agg: metric.agg ?? null, ts: pgToTs(pgForMetric(metric.agg)) };
    }
    models[model.name] = { dimensions, metrics };
  }

  const topMetrics = [
    ...new Set((graph.top_level_metrics || []).map((metric) => metric.name).filter((name) => !modelMetricNames.has(name))),
  ].sort();

  return { models, topMetrics };
}

function emitClientSchema(schema, yaml) {
  let out = "/* Generated by `sidemantic gen types`. Do not edit by hand. */\n\n";
  out += `export const schema = ${JSON.stringify(schema, null, 2)} as const;\n\n`;
  out += "export type Schema = typeof schema;\n";
  if (yaml != null) {
    out += `\nexport const SCHEMA_YAML = ${JSON.stringify(yaml)} as const;\n`;
  }
  return out;
}

/**
 * Generate the typed-client schema module from Sidemantic YAML model definitions.
 *
 * @param {string} models  Sidemantic YAML model definitions.
 * @param {object} [opts]
 * @param {boolean} [opts.includeYaml=true]  Embed the models as `SCHEMA_YAML` (for the wasm transport).
 * @param {string|URL} [opts.wasmUrl]  Override the wasm binary location.
 * @returns {Promise<string>} TypeScript source.
 */
export async function generateClientSchema(models, { includeYaml = true, wasmUrl } = {}) {
  const runtime = await createSidemanticRuntime(wasmUrl ? { wasmUrl } : {});
  const graph = runtime.loadGraph(models);
  const schema = buildClientSchema(graph);
  return emitClientSchema(schema, includeYaml ? models : null);
}

// ---------------------------------------------------------------------------
// sqlx-style typed semantic SQL (JS counterpart to `sidemantic gen sql`)
// ---------------------------------------------------------------------------

const PARAM_TS = { string: "string", number: "number", date: "string", yesno: "boolean", unquoted: "string" };
const PARAM_STUB = { string: "'x'", number: "0", date: "'2000-01-01'", yesno: "TRUE", unquoted: "1" };
const PARAM_RE = /\{\{\s*(\w+)\s*\}\}/g;
const CALL_LITERAL_RE = /(`[^`]*`|"[^"]*"|'[^']*')/;

/** Extract `<call>(...)` semantic-SQL literals from TypeScript source (skips ${} / escapes). */
export function extractSqlLiterals(sources, { call = "query" } = {}) {
  const pattern = new RegExp(`\\b${call}\\s*\\(\\s*` + CALL_LITERAL_RE.source, "gs");
  const literals = [];
  for (const text of sources) {
    for (const match of text.matchAll(pattern)) {
      const content = match[1].slice(1, -1);
      if (!content || content.includes("${") || content.includes("\\")) continue;
      if (!literals.includes(content)) literals.push(content);
    }
  }
  return literals;
}

function indexGraph(graph) {
  const metrics = new Set();
  const dimensions = new Set();
  const paramType = new Map();
  for (const parameter of graph.parameters || []) paramType.set(parameter.name, parameter.type);
  for (const model of graph.models || []) {
    for (const metric of model.metrics || []) metrics.add(`${model.name}.${metric.name}`);
    for (const dimension of model.dimensions || []) {
      dimensions.add(`${model.name}.${dimension.name}`);
      const grains = dimension.effective_granularities || (dimension.type === "time" ? TIME_GRANULARITIES : []);
      for (const grain of grains) dimensions.add(`${model.name}.${dimension.name}__${grain}`);
    }
  }
  for (const metric of graph.top_level_metrics || []) metrics.add(metric.name);
  return { metrics, dimensions, paramType };
}

function stripComments(sql) {
  return sql.replace(/--[^\n]*/g, " ").replace(/\/\*[\s\S]*?\*\//g, " ");
}

function selectList(sql) {
  const clean = stripComments(sql);
  const lower = clean.toLowerCase();
  const start = lower.indexOf("select");
  if (start < 0) throw new Error(`not a SELECT: ${sql}`);
  let depth = 0;
  for (let i = start + 6; i < clean.length; i += 1) {
    const ch = clean[i];
    if (ch === "(") depth += 1;
    else if (ch === ")") depth -= 1;
    else if (depth === 0 && lower.startsWith("from", i) && /\s|\(/.test(clean[i - 1] || " ") && /\s/.test(clean[i + 4] || " ")) {
      return clean.slice(start + 6, i);
    }
  }
  throw new Error(`SELECT without FROM is not supported: ${sql}`);
}

function splitProjections(list) {
  const parts = [];
  let depth = 0;
  let current = "";
  for (const ch of list) {
    if (ch === "(") depth += 1;
    else if (ch === ")") depth -= 1;
    if (ch === "," && depth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  if (current.trim()) parts.push(current);
  return parts.map((part) => part.trim()).filter(Boolean);
}

function parseProjections(sql, index) {
  return splitProjections(selectList(sql)).map((projection) => {
    const asMatch = /\s+as\s+([A-Za-z_]\w*)\s*$/i.exec(projection);
    const ref = (asMatch ? projection.slice(0, asMatch.index) : projection).trim();
    const alias = asMatch ? asMatch[1] : null;
    let kind;
    if (index.metrics.has(ref)) kind = "metric";
    else if (index.dimensions.has(ref)) kind = "dimension";
    else throw new Error(`Unknown or unsupported reference '${ref}' in: ${sql}`);
    return { ref, alias, kind };
  });
}

function stubParams(sql, index) {
  return sql.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, name) => PARAM_STUB[index.paramType.get(name)] || "'x'");
}

function tsObject(pairs) {
  if (!pairs.length) return "{}";
  return "{ " + pairs.map(([name, ts]) => `${JSON.stringify(name)}: ${ts}`).join("; ") + " }";
}

/**
 * Generate a `GeneratedQueries` interface from semantic-SQL literals (sqlx-style).
 * Projections are classified against the loaded graph; result types come from the
 * wasm `resultSchema` export (authoritative aliasing, incl. `{model}_{leaf}`).
 *
 * @param {string} models  Sidemantic YAML model definitions.
 * @param {string[]} queries  Semantic SQL strings.
 * @param {object} [opts]
 * @param {string|URL} [opts.wasmUrl]
 * @returns {Promise<string>} TypeScript source.
 */
export async function generateSqlTypes(models, queries, { wasmUrl } = {}) {
  const runtime = await createSidemanticRuntime(wasmUrl ? { wasmUrl } : {});
  const index = indexGraph(runtime.loadGraph(models));

  const entries = queries.map((sql) => {
    // Best-effort full-query validation: run the whole query through the engine (rejects
    // malformed SQL), then validate + type the projection below. Param placeholders are
    // stubbed so the SQL parses. (The wasm rewriter is more lenient on subtle syntax than
    // the Python `gen sql` path, which parses with sqlglot.)
    runtime.rewrite(models, stubParams(sql, index));
    const projections = parseProjections(sql, index);
    const dimensions = projections.filter((projection) => projection.kind === "dimension");
    const metrics = projections.filter((projection) => projection.kind === "metric");
    // resultSchema returns columns in dimensions-then-metrics order, matching this concat;
    // an explicit `AS` alias overrides the engine's bare-leaf output name.
    const ordered = [...dimensions, ...metrics];
    const columns = runtime.resultSchema(models, {
      metrics: metrics.map((projection) => projection.ref),
      dimensions: dimensions.map((projection) => projection.ref),
    });
    const rowPairs = columns.map((column, position) => [ordered[position]?.alias || column.name, pgToTs(column.data_type)]);
    const params = [...new Set([...sql.matchAll(PARAM_RE)].map((match) => match[1]))];
    const paramPairs = params.map((name) => [name, PARAM_TS[index.paramType.get(name)] || "string"]);
    return `  ${JSON.stringify(sql)}: {\n    row: ${tsObject(rowPairs)};\n    params: ${tsObject(paramPairs)};\n  };`;
  });

  return (
    "/* Generated by `sidemantic gen sql`. Do not edit by hand. */\n" +
    "export interface GeneratedQueries {\n" +
    entries.join("\n") +
    "\n}\n"
  );
}
