// In-browser / Node TypeScript codegen, the JS counterpart to `sidemantic gen types`.
// Runs the wasm to introspect a semantic layer and emits the same `as const` schema
// the Python generator produces (byte-identical for the client schema), so either
// generator can feed the shared `sidemantic-wasm/client` runtime.

import { createSidemanticRuntime } from "./index.js";

const TIME_GRANULARITIES = ["second", "minute", "hour", "day", "week", "month", "quarter", "year"];

// Postgres/DuckDB data type -> TS scalar tag (mirrors sidemantic-wasm/client ScalarTag).
const PG_TO_TS = {
  BIGINT: "number",
  NUMERIC: "number",
  DECIMAL: "number",
  DOUBLE: "number",
  REAL: "number",
  INTEGER: "number",
  BOOLEAN: "boolean",
};

function pgToTs(pgType) {
  return PG_TO_TS[String(pgType).toUpperCase()] || "string";
}

// Mirror sidemantic/core/catalog.py exactly so JS output matches the Python generator.
function pgForDimension(dimType, granularity) {
  if (dimType === "categorical") return "VARCHAR";
  if (dimType === "numeric") return "NUMERIC";
  if (dimType === "time") return ["day", "week", "month", "quarter", "year"].includes(granularity) ? "DATE" : "TIMESTAMP";
  if (dimType === "boolean") return "BOOLEAN";
  return "VARCHAR";
}

function pgForMetric(agg) {
  return agg === "count" || agg === "count_distinct" ? "BIGINT" : "NUMERIC";
}

function byName(a, b) {
  return a.name < b.name ? -1 : a.name > b.name ? 1 : 0;
}

/** Build the `schema` payload from a parsed wasm graph (matches build_client_schema in Python). */
export function buildClientSchema(graph) {
  const modelList = [...(graph.models || [])].sort(byName);
  // The wasm runtime copies each top-level metric onto its owner model (for compilation) and
  // lists it in top_level_metrics; the Python graph keeps them graph-level only. Identify the
  // owner-assigned copies by value (they are byte-identical to the top_level_metrics entry) so we
  // can drop just those from per-model metrics — keeping a genuine model metric that merely shares
  // a name with a different top-level metric, and avoiding an invalid `orders.finance.x` for a
  // namespaced top metric. They stay queryable as a bare ref via topMetrics below.
  const topMetricByName = new Map((graph.top_level_metrics || []).map((metric) => [metric.name, JSON.stringify(metric)]));

  const models = {};
  for (const model of modelList) {
    const dimensions = {};
    for (const dimension of [...(model.dimensions || [])].sort(byName)) {
      const entry = { kind: dimension.type, ts: pgToTs(pgForDimension(dimension.type, dimension.granularity)) };
      if (dimension.type === "time") {
        const grains = dimension.supported_granularities;
        entry.grains = grains && grains.length ? grains : TIME_GRANULARITIES;
      }
      dimensions[dimension.name] = entry;
    }
    const metrics = {};
    for (const metric of [...(model.metrics || [])].sort(byName)) {
      // Skip only an owner-assigned copy of a top-level metric (identical to the top-level entry).
      if (topMetricByName.get(metric.name) === JSON.stringify(metric)) continue;
      metrics[metric.name] = { agg: metric.agg ?? null, ts: pgToTs(pgForMetric(metric.agg)) };
    }
    models[model.name] = { dimensions, metrics };
  }

  // List every top-level metric as a bare ref, even one whose leaf name also exists as a model
  // metric — the runtime resolves both the bare and model-qualified forms.
  const topMetrics = [...topMetricByName.keys()].sort();

  return { models, topMetrics };
}

function emitClientSchema(schema, yaml) {
  let out = "/* Generated by `sidemantic gen types`. Do not edit by hand. */\n\n";
  out += `export const schema = ${JSON.stringify(schema, null, 2)} as const;\n\n`;
  out += "export type Schema = typeof schema;\n";
  if (yaml != null) {
    out += `\nexport const SCHEMA_YAML = ${JSON.stringify(yaml)} as const;\n`;
  }
  return out;
}

/**
 * Generate the typed-client schema module from Sidemantic YAML model definitions.
 *
 * @param {string} models  Sidemantic YAML model definitions.
 * @param {object} [opts]
 * @param {boolean} [opts.includeYaml=true]  Embed the models as `SCHEMA_YAML` (for the wasm transport).
 * @param {string|URL} [opts.wasmUrl]  Override the wasm binary location.
 * @returns {Promise<string>} TypeScript source.
 */
export async function generateClientSchema(models, { includeYaml = true, wasmUrl } = {}) {
  const runtime = await createSidemanticRuntime(wasmUrl ? { wasmUrl } : {});
  const graph = runtime.loadGraph(models);
  const schema = buildClientSchema(graph);
  return emitClientSchema(schema, includeYaml ? models : null);
}

// ---------------------------------------------------------------------------
// sqlx-style typed semantic SQL (JS counterpart to `sidemantic gen sql`)
// ---------------------------------------------------------------------------

const PARAM_TS = { string: "string", number: "number", date: "string", yesno: "boolean", unquoted: "string" };
const PARAM_STUB = { string: "'x'", number: "0", date: "'2000-01-01'", yesno: "TRUE", unquoted: "1" };
const PARAM_RE = /\{\{\s*(\w+)\s*\}\}/g;
const CALL_LITERAL_RE = /(`[^`]*`|"[^"]*"|'[^']*')/;

// Blank out `//` and `/* */` comments while leaving string/template literals intact, so a
// commented-out `// query("...")` is not scanned and `//` inside a quoted SQL string (e.g.
// `'http://%'`) is not mistaken for a comment. A scanner, not a regex, for that reason.
function stripTsComments(text) {
  let out = "";
  let quote = null;
  for (let i = 0; i < text.length; i += 1) {
    const ch = text[i];
    if (quote !== null) {
      out += ch;
      if (ch === "\\" && i + 1 < text.length) {
        out += text[i + 1];
        i += 1;
      } else if (ch === quote) {
        quote = null;
      }
      continue;
    }
    if (ch === '"' || ch === "'" || ch === "`") {
      quote = ch;
      out += ch;
      continue;
    }
    if (ch === "/" && text[i + 1] === "/") {
      const newline = text.indexOf("\n", i);
      if (newline === -1) break;
      i = newline - 1; // loop's i += 1 lands on the newline, which we keep
      continue;
    }
    if (ch === "/" && text[i + 1] === "*") {
      const end = text.indexOf("*/", i + 2);
      i = end === -1 ? text.length : end + 1;
      out += " ";
      continue;
    }
    out += ch;
  }
  return out;
}

/** Extract `<call>(...)` semantic-SQL literals from TypeScript source (strips comments, skips ${} / escapes). */
export function extractSqlLiterals(sources, { call = "query" } = {}) {
  const pattern = new RegExp(`\\b${call}\\s*\\(\\s*` + CALL_LITERAL_RE.source, "gs");
  const literals = [];
  for (const rawText of sources) {
    const text = stripTsComments(rawText);
    for (const match of text.matchAll(pattern)) {
      const content = match[1].slice(1, -1);
      if (!content || content.includes("${") || content.includes("\\")) continue;
      if (!literals.includes(content)) literals.push(content);
    }
  }
  return literals;
}

function indexGraph(graph) {
  const metrics = new Set();
  const dimensions = new Set();
  const models = new Map();
  const paramType = new Map();
  for (const parameter of graph.parameters || []) paramType.set(parameter.name, parameter.type);
  for (const model of graph.models || []) {
    models.set(model.name, model);
    for (const metric of model.metrics || []) metrics.add(`${model.name}.${metric.name}`);
    for (const dimension of model.dimensions || []) {
      dimensions.add(`${model.name}.${dimension.name}`);
      const grains = dimension.effective_granularities || (dimension.type === "time" ? TIME_GRANULARITIES : []);
      for (const grain of grains) dimensions.add(`${model.name}.${dimension.name}__${grain}`);
    }
  }
  for (const metric of graph.top_level_metrics || []) metrics.add(metric.name);
  return { metrics, dimensions, models, paramType };
}

function stripComments(sql) {
  return sql.replace(/--[^\n]*/g, " ").replace(/\/\*[\s\S]*?\*\//g, " ");
}

// True when keyword `kw` sits at index `i` with SQL word boundaries (not inside an identifier).
function keywordAt(lower, src, i, kw) {
  if (!lower.startsWith(kw, i)) return false;
  const before = i === 0 ? " " : src[i - 1];
  const after = src[i + kw.length] ?? " ";
  return /[\s(),]/.test(before) && /[\s(]/.test(after);
}

// The outer statement, starting at its top-level SELECT, skipping a leading CTE
// (`WITH x AS (SELECT ...) SELECT ...`). Projection + FROM/alias inference run on this so a CTE
// body's SELECT/FROM is never mistaken for the statement's output query.
function outerStatement(sql) {
  const clean = stripComments(sql);
  const lower = clean.toLowerCase();
  let depth = 0;
  for (let i = 0; i < clean.length; i += 1) {
    const ch = clean[i];
    if (ch === "(") depth += 1;
    else if (ch === ")") depth -= 1;
    else if (depth === 0 && keywordAt(lower, clean, i, "select")) return clean.slice(i);
  }
  throw new Error(`not a SELECT: ${sql}`);
}

// Projection list of a statement that begins with its (outer) SELECT.
function selectList(statement) {
  const lower = statement.toLowerCase();
  let depth = 0;
  for (let i = 6; i < statement.length; i += 1) {
    const ch = statement[i];
    if (ch === "(") depth += 1;
    else if (ch === ")") depth -= 1;
    else if (depth === 0 && keywordAt(lower, statement, i, "from")) return statement.slice(6, i);
  }
  throw new Error(`SELECT without FROM is not supported: ${statement}`);
}

function splitProjections(list) {
  const parts = [];
  let depth = 0;
  let current = "";
  for (const ch of list) {
    if (ch === "(") depth += 1;
    else if (ch === ")") depth -= 1;
    if (ch === "," && depth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  if (current.trim()) parts.push(current);
  return parts.map((part) => part.trim()).filter(Boolean);
}

const FROM_KEYWORDS = /^(on|where|group|order|limit|having|join|left|right|inner|outer|full|cross|using|as)$/i;

// Map table aliases (and model names) to model names from FROM/JOIN clauses, plus the default
// (first) model, so bare and aliased projections resolve like the engine's rewriter.
function parseFromAliases(sql) {
  const aliases = new Map();
  let defaultModel = null;
  const pattern = /\b(?:from|join)\s+([A-Za-z_]\w*)(?:\s+(?:as\s+)?([A-Za-z_]\w*))?/gi;
  for (const match of stripComments(sql).matchAll(pattern)) {
    const [, model, alias] = match;
    if (defaultModel === null) defaultModel = model;
    aliases.set(model, model);
    if (alias && !FROM_KEYWORDS.test(alias)) aliases.set(alias, model);
  }
  return { aliases, defaultModel };
}

// Resolve a raw projection ref to a model-qualified ref: `o.revenue` -> `orders.revenue`
// (table alias), `revenue` -> `orders.revenue` (bare, default model), or a bare top-level metric.
function resolveRef(rawRef, from, index) {
  const dot = rawRef.indexOf(".");
  if (dot !== -1) {
    const resolved = `${from.aliases.get(rawRef.slice(0, dot)) || rawRef.slice(0, dot)}.${rawRef.slice(dot + 1)}`;
    if (index.metrics.has(resolved)) return { ref: resolved, kind: "metric" };
    if (index.dimensions.has(resolved)) return { ref: resolved, kind: "dimension" };
    return null;
  }
  if (from.defaultModel) {
    const qualified = `${from.defaultModel}.${rawRef}`;
    if (index.metrics.has(qualified)) return { ref: qualified, kind: "metric" };
    if (index.dimensions.has(qualified)) return { ref: qualified, kind: "dimension" };
  }
  if (index.metrics.has(rawRef)) return { ref: rawRef, kind: "metric" };
  return null;
}

// Expand `*` / `model.*` to the model's dimensions then metrics in definition order, matching the
// rewriter + Python `gen sql`. A bare `*` uses the FROM (default) model.
function expandStar(tableRef, from, index, sql) {
  const modelName = tableRef ? from.aliases.get(tableRef) || tableRef : from.defaultModel;
  const model = modelName && index.models.get(modelName);
  if (!model) throw new Error(`Cannot expand '*' for unknown model '${modelName || tableRef}' in: ${sql}`);
  return [
    ...(model.dimensions || []).map((dimension) => ({ ref: `${modelName}.${dimension.name}`, alias: null, kind: "dimension" })),
    ...(model.metrics || []).map((metric) => ({ ref: `${modelName}.${metric.name}`, alias: null, kind: "metric" })),
  ];
}

function parseProjections(sql, index) {
  const statement = outerStatement(sql);
  const from = parseFromAliases(statement);
  return splitProjections(selectList(statement)).flatMap((projection) => {
    // Star projection: `*` or `model.*`.
    const star = /^(?:([A-Za-z_]\w*)\s*\.\s*)?\*$/.exec(projection.trim());
    if (star) return expandStar(star[1], from, index, sql);
    // Explicit `expr AS alias`.
    const asMatch = /\s+as\s+([A-Za-z_]\w*)\s*$/i.exec(projection);
    let rawRef = (asMatch ? projection.slice(0, asMatch.index) : projection).trim();
    let alias = asMatch ? asMatch[1] : null;
    let resolved = resolveRef(rawRef, from, index);
    // Implicit trailing alias `expr alias` (no AS), e.g. `orders.revenue sales`. Only split when
    // the leading part resolves on its own, so a single ref is never mistaken for ref+alias. The
    // engine + Python `gen sql` (via sqlglot) both treat the trailing token as the output alias.
    if (!resolved && !asMatch) {
      const implicit = /^(.*\S)\s+([A-Za-z_]\w*)\s*$/.exec(rawRef);
      const head = implicit && resolveRef(implicit[1].trim(), from, index);
      if (head) {
        resolved = head;
        rawRef = implicit[1].trim();
        alias = implicit[2];
      }
    }
    if (!resolved) throw new Error(`Unknown or unsupported reference '${rawRef}' in: ${sql}`);
    return [{ ref: resolved.ref, alias, kind: resolved.kind }];
  });
}

function stubParams(sql, index) {
  return sql.replace(/\{\{\s*(\w+)\s*\}\}/g, (_match, name) => PARAM_STUB[index.paramType.get(name)] || "'x'");
}

// Drop a leading DISTINCT/ALL modifier from the SELECT used for analysis. It does not change the
// result column types, but the wasm rewriter rejects it and it would otherwise reach resolveRef as
// part of the first projection. The original SQL (with the modifier) stays the generated type key.
function stripSelectModifiers(sql) {
  return sql.replace(/(\bselect\s+)(?:distinct|all)\b\s*/i, "$1");
}

// True when the outer SELECT projects a star (`*` / `model.*`). The wasm rewriter rejects star
// queries, so codegen skips the full-query rewrite check and expands the star from validated model
// fields (parseProjections) instead — matching the Python `gen sql` path, which expands `*` too.
function isStarQuery(sql) {
  try {
    return splitProjections(selectList(outerStatement(sql))).some((part) => /^(?:[A-Za-z_]\w*\s*\.\s*)?\*$/.test(part.trim()));
  } catch {
    return false;
  }
}

function tsObject(pairs) {
  if (!pairs.length) return "{}";
  return "{ " + pairs.map(([name, ts]) => `${JSON.stringify(name)}: ${ts}`).join("; ") + " }";
}

/**
 * Generate a `GeneratedQueries` interface from semantic-SQL literals (sqlx-style).
 * Projections are classified against the loaded graph; result types come from the
 * wasm `resultSchema` export (authoritative aliasing, incl. `{model}_{leaf}`).
 *
 * @param {string} models  Sidemantic YAML model definitions.
 * @param {string[]} queries  Semantic SQL strings.
 * @param {object} [opts]
 * @param {string|URL} [opts.wasmUrl]
 * @returns {Promise<string>} TypeScript source.
 */
export async function generateSqlTypes(models, queries, { wasmUrl } = {}) {
  const runtime = await createSidemanticRuntime(wasmUrl ? { wasmUrl } : {});
  const index = indexGraph(runtime.loadGraph(models));

  const entries = queries.map((sql) => {
    // Analyze a copy with SELECT modifiers (DISTINCT/ALL) removed — they do not affect column
    // types but the wasm rewriter rejects them; the original `sql` stays the generated type key.
    const analyzed = stripSelectModifiers(sql);
    // Best-effort full-query validation: run the whole query through the engine (rejects
    // malformed SQL), then validate + type the projection below. Param placeholders are
    // stubbed so the SQL parses. (The wasm rewriter is more lenient on subtle syntax than
    // the Python `gen sql` path, which parses with sqlglot.)
    if (!isStarQuery(analyzed)) runtime.rewrite(models, stubParams(analyzed, index));
    const projections = parseProjections(analyzed, index);
    const metrics = projections.filter((projection) => projection.kind === "metric");
    const dimensions = projections.filter((projection) => projection.kind === "dimension");
    const queryRefs = { metrics: metrics.map((p) => p.ref), dimensions: dimensions.map((p) => p.ref) };

    // The authoritative output: includes any default time dimension the engine inserts for a
    // metric's owner model (e.g. a top-level metric like `revenue_per_order` pulls in
    // `orders.created_at__month`), so the row type matches what the query actually returns.
    const columns = runtime.resultSchema(models, queryRefs);
    // The same projections with engine-inserted defaults suppressed: aligned 1:1 (dims, then
    // metrics) with `ordered`, so we can tell which `columns` are explicit projections (and
    // carry an `AS` alias) vs. engine-inserted dimensions (keep their bare output name).
    const explicitColumns = runtime.resultSchema(models, { ...queryRefs, skip_default_time_dimensions: true });
    const ordered = [...dimensions, ...metrics];
    let explicitIndex = 0;
    const rowPairs = columns.map((column) => {
      if (explicitIndex < explicitColumns.length && column.name === explicitColumns[explicitIndex].name) {
        const alias = ordered[explicitIndex]?.alias;
        explicitIndex += 1;
        return [alias || column.name, pgToTs(column.data_type)];
      }
      return [column.name, pgToTs(column.data_type)];
    });
    const params = [...new Set([...sql.matchAll(PARAM_RE)].map((match) => match[1]))];
    const paramPairs = params.map((name) => [name, PARAM_TS[index.paramType.get(name)] || "string"]);
    return `  ${JSON.stringify(sql)}: {\n    row: ${tsObject(rowPairs)};\n    params: ${tsObject(paramPairs)};\n  };`;
  });

  const paramTypeEntries = queries.map((sql) => {
    const params = [...new Set([...sql.matchAll(PARAM_RE)].map((match) => match[1]))];
    const paramTypes = Object.fromEntries(params.map((name) => [name, index.paramType.get(name) || "string"]));
    return `  ${JSON.stringify(sql)}: ${JSON.stringify(paramTypes)},`;
  });

  return (
    "/* Generated by `sidemantic gen sql`. Do not edit by hand. */\n" +
    "export interface GeneratedQueries {\n" +
    entries.join("\n") +
    "\n}\n" +
    "\n" +
    "export const queryParamTypes = {\n" +
    paramTypeEntries.join("\n") +
    "\n} as const;\n"
  );
}
